export const naming = [{resource:'hljs', target:''},
    {resource:'elixir', target:''},
    {resource:'hljs-variable', target:'code-variable'},
    {resource:'hljs-template-variable', target:'code-template-variable'},
    {resource:'hljs-attribute', target:'code-attribute'},
    {resource:'hljs-deletion', target:'code-deletion'},
    {resource:'hljs-string', target:'code-string'},
    {resource:'hljs-built_in', target:'code-built_in'},
    {resource:'hljs-builtin-name', target:'code-builtin-name'},
    {resource:'hljs-addition', target:'code-addition'},
    {resource:'hljs-comment', target:'code-comment'},
    {resource:'hljs-quote', target:'code-quote'},
    {resource:'hljs-meta', target:'code-meta'},
    {resource:'hljs-keyword', target:'code-keyword'},
    {resource:'hljs-selector-tag', target:'code-selector-tag'},
    {resource:'hljs-tag', target:'code-tag'},
    {resource:'hljs-title', target:'code-title'},
    {resource:'hljs-name', target:'code-name'},
    {resource:'hljs-selector-id', target:'code-selector-id'},
    {resource:'hljs-selector-class', target:'code-selector-class'},
    {resource:'hljs-section', target:'code-section'},
    {resource:'hljs-type', target:'code-type'},
]